# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NaN is not NIL
email: d @at@ mardie.net
description: > # this means to ignore newlines until "baseurl:"
  Diego Marquina
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mardie.net" # the base hostname & protocol for your site
twitter_username: _mardie
github_username:  mardie
permalink: "/:year/:month/:day/:title"
collections:
  projects:
    output: true
    title: Projects
    permalink: /projects/:title

# Build settings
markdown: kramdown
